name: core_storage
description: Abstração para armazenamento local na arquitetura modular Flutter
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  core_interfaces:
    path: ../core_interfaces
  
  # Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.0.0
  path_provider: ^2.1.1
  
  # Utils
  equatable: ^2.0.7
  meta: ^1.9.1
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: false
