name: core_analytics
description: Abstração para telemetria e analytics na arquitetura modular Flutter
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  core_interfaces:
    path: ../core_interfaces
  
  # Utils
  equatable: ^2.0.7
  meta: ^1.9.1
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: false
