name: pix
description: Micro app de Pix para a arquitetura modular Flutter
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Core packages
  core_interfaces:
    path: ../../core/core_interfaces
  core_network:
    path: ../../core/core_network
  core_storage:
    path: ../../core/core_storage
  core_analytics:
    path: ../../core/core_analytics
  
  # Shared packages
  design_system:
    path: ../../shared/design_system
  shared_utils:
    path: ../../shared/shared_utils
  
  # State Management
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.7
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Navigation
  go_router: ^12.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  
  # Utils
  meta: ^1.9.1
  uuid: ^4.1.0
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
